# Generated by Django 5.2.15 on 2026-06-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Номер лицевого счёта')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Баланс')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Лицевой счёт',
                'verbose_name_plural': 'Лицевые счета',
                'ordering': ['account_number'],
            },
        ),
    ]
