# Generated by Django 5.0.14 on 2026-06-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='compression',
            field=models.CharField(choices=[('high', 'Высокое (90%, макс. качество)'), ('medium', 'Среднее (70%, оптимально)'), ('low', 'Низкое (50%, макс. сжатие)')], default='high', help_text='Высокое — макс. качество для слайдера. Среднее — оптимально для general. Низкое — макс. экономия места.', max_length=10, verbose_name='Сжатие'),
        ),
        migrations.AddField(
            model_name='product',
            name='compression',
            field=models.CharField(choices=[('high', 'Высокое (90%, макс. качество)'), ('medium', 'Среднее (70%, оптимально)'), ('low', 'Низкое (50%, макс. сжатие)')], default='high', help_text='Высокое — макс. качество для слайдера. Среднее — оптимально для general. Низкое — макс. экономия места.', max_length=10, verbose_name='Сжатие'),
        ),
    ]
